# Generated by Django 4.0.5 on 2022-08-21 18:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.TimeField(default=datetime.datetime(2022, 8, 21, 18, 56, 10, 546056, tzinfo=utc))),
                ('end_time', models.TimeField(default=datetime.datetime(2022, 8, 21, 18, 56, 10, 546056, tzinfo=utc))),
                ('done', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('task_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
