# Generated by Django 4.0.5 on 2022-08-21 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_todolist_created_alter_todolist_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
