# Generated by Django 4.0.5 on 2022-08-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0005_alter_todolist_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='task_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
