# Generated by Django 4.0.5 on 2022-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_todolist_end_time_alter_todolist_task_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='end_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
