# Generated by Django 4.0.5 on 2022-08-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_todolist_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='task_manager',
        ),
    ]
