# Generated by Django 4.0.5 on 2022-08-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0003_products_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productImage',
        ),
    ]
