# Generated by Django 4.0.5 on 2022-08-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0004_remove_products_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.CharField(default='technology', max_length=100),
        ),
    ]
