# Generated by Django 4.0.5 on 2022-07-01 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0003_alter_todo_begins_alter_todo_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
