# Generated by Django 4.0.5 on 2022-08-06 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0004_todo_end_date_todo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='begins',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ends',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
